name: Test

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t test .

      - name: Test
        run: docker run --rm test eb --version
